#!/bin/bash

# Example: "/bin/bash /home/docker/cassandra cassandra 1

docker network create -d overlay overlay

DIRECTORY="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
HUBUSER=devcamaws

docker rmi cassandra
docker rmi $HUBUSER/$1

cd $DIRECTORY/filedocker/cassandra/

docker build -t $1 .

docker tag $1 $HUBUSER/$1

cat $DIRECTORY/hubdockpass | docker login --username $HUBUSER --password-stdin

docker push $HUBUSER/$1


docker service create --name $1 -p 9042:9042 \
            --with-registry-auth \
            --network overlay \
            --constraint=node.role==worker \
            --endpoint-mode dnsrr \
            --env-file $DIRECTORY/filedocker/cassandra/cassandra-env \
            -d $HUBUSER/$1